---
title: "Further reading"
---

For an expanded coverage how the topics discussed during the course can be implemented in R, see @pebesma2022, @tennekes2022, @bivand2023, @gimond2023, @moraga2023 and @lovelace2024.

For more details on GIS and mapping, see @crampton2010 and @bolstad2023. The series of blogposts, [The "correct" map](https://www.cartographerstale.com/p/the-correct-map) and [The true size of countries](https://www.cartographerstale.com/p/the-true-size-of-countries) by Miguel García Álvarez provides a very useful overview of Coordinate Reference Systems and cartographic projections. Also, for an entertaining and didactic introduction to maps in general, see Paulina Rowińska's book: [Mapmatics: A mathematician's guide to navigating the world](https://www.hup.harvard.edu/books/9780674294233). 

For a more detailed discussion on how historians use GIS tools, see @gregory2007, @knowles2008, @marti2011, @gregory2014, @gregory2018; @lawson2021, @travis2020, @cole2022, @mogorovich2022 and @mcdonough2024. Spatial history nonetheless comes in a variety of forms, not necessarily involving using GIS tools [@bavaj2022b]. Maps actually constitute another historical *source*, so they contain useful information that helps knowing more about the past. In this regard, historians of maps and mapping practices often study maps as cultural objects [@mcdonough2024, p. 99]. @schulten2012 and @spychal2024, for instance, trace the growing use of maps in the US and UK during the 19^th^ century as tools for shaping history, policy and national identity.

For the humanities in general see @bodenhamer2010, @presner2015 and @bodenhamer2010 for a discussion on the geospatial turn in the humanities in general. @cooper2016 is specifically aimed at mapping in literary studies.

For the social social sciences, especially for economics, see @overman2010 or @kudamatsu2018. In this field, it is common to model spatial dependencies in regression analysis. An introduction in R can be found in @bivand2023 [ch. 17]. Taro Mieno is writing a book entitled [R as GIS for Economists](https://tmieno2.github.io/R-as-GIS-for-Economists-Quarto/). Likewise, the growing use of satellite data in economics is surveyed in @donaldson2016. 



