---
title: "Instructions"
---

Below are the instructions to prepare the session in advance: 

**1. Install R and RStudio**. **R** is a (free) statistical software and **RStudio** is an integrated interface that makes working with R easier. Bear in mind that you have to download and install both softwares: R and RStudio. The version you install depends on whether you are using Windows or Mac. Here is a [link](https://posit.co/download/rstudio-desktop/) to access them.

**2. Install QGIS**. Although we will mostly be working with R, we will need QGIS for digitising spatial features manually (from historical maps). **QGIS** is a geographic information system (GIS) software, which is also free and open-source. You can find the instructions to download and install QGIS [here](https://www.qgis.org).

**3. Download the course materials** (available in Blackboard). These include the [datasets]{.underline} we will be working with and the [R scripts]{.underline} containing the code to map the information they contain (or extract other spatial information). Create a dedicated folder to this session in your computer. Name it `mapping` and store these files in separate folders (named `data` and `scripts`, respectively) within the folder `mapping`.

**5. Get familiar with R and RStudio** by opening **RStudio** and following the instructions in the [Intro to R](get-r.html) section.  
  
**6. Read the blogposts and online visualisations in advance listed [here](coursework.html)**. 

**7. Do not forget to bring your laptop to the session (or work in pairs)**.

\vspace{1em}

Do not hesitate to contact me if you have any question!
